### ISSUE TITLE
데이터 구성 및 포맷 최종화

### ISSUE THREAD

**Issue by pingpingy1** [NewWays-TechForImpactKAIST/API-scrap-and-analysis#55]
## 문제 상황
데이터 수집 포맷을 통일하고자 많은 노력이 들어갔음에도 불구, 아직 명확히 결정되지 않은 사항들이 있고, 이로 인해 코드 작성 및 관리가 어려운 경우가 있습니다.
- 변수 이름: 정당은 party vs jdName, API의 camelCase vs 파이썬의 snake_case 등
- 저장할 정보 종류: API에서 얻어온 정보 중, 스키마에 포함되는 것은 극히 일부분
- 데이터베이스 구조: 현재 local_council 컬렉션에는 각 기초지역 별 의원들이 리스트로 저장되어 있지만 스키마에는 기초의원을 하나의 릴레이션으로 정의, 스키마에는 데이터베이스와 컬렉션 구분이 없음 등
얼마 남지 않은 최종 발표 전까지 큰 오류 없이 개발을 진행하려면, 프로젝트 목표가 설정되었지만 아직 개발 초기 단계일 때 이러한 자잘한 사항들에 대해 명확히 합의하는 것이 좋다고 생각합니다.

## 해결 방안 제안
내일 (11/17) 모이는 시간에 데이터베이스 스키마와 변수 이름 convention을 명확히 정립하는 것이 어떨까 제안해봅니다.
이 사안들이 결정된다면 제가 ScrapResult를 비롯한 데이터 반환 포맷을 수정할 수 있을 것 같습니다.

**Comment by Re-st** [comment]
변수 이름: 정당은 jdName, 파이썬의 snake_case 

(이거 성민님께 보내기)
선거구명	sggName	50	옵션	전주시을	선거구명
시도명	sdName	40	옵션	전라북도	시도명
구시군명	wiwName	40	옵션	전주시완산구	구시군명
정당명	jdName	50	옵션	OO당	정당명
한글성명	name	50	옵션	홍길동	한글성명
성별	gender	1	옵션	남	성별
생년월일	birthday	8	옵션	19000000	생년월일
연령	age	2	옵션	0	연령
직업ID	jobId	2	옵션	1	직업ID
직업	job	200	옵션	정치인	직업
학력ID	eduId	2	옵션	1	학력ID
학력	edu	200	옵션	대졸	학력
빼고 다 지우기. https://www.data.go.kr/data/15000864/openapi.do#/tab_layer_detail_function 참고.
DataClass에다가 필요한 것만 정의하기. 나머지는 날라간다. <- 


mongoDB council id = 1. list = .....  
다이어그램은 local_distrct table이 있고, councilor table이 있고, .. 그 안에 local id 를 key로 reference. <- 로 바꾸기
mongodb 8개의 db를 만들어서 각각 넣어주면 된다.



희원 : 이 사안들이 결정된다면 제가 ScrapResult를 비롯한 데이터 반환 포맷을 수정할 수 있을 것 같습니다.

박건 : mongoDB 전체적 수정

성민 : DataClass 클래스 제작

**Comment by keonly** [comment]
현재 구현상 API로부터 받아온 정보를 해당하는 지역구 ID 오브젝트에 넣어줄 때 `district` 데이터베이스의 `local_district` 컬렉션에 있는 `sdName`과 `wiwName`을 매칭해서 ID를 받아오고 있습니다.

[`sdName`과 `wiwName`은 API에서 받아온 필드 이름이라서 그대로 유지하는 게 좋을 것 같습니다.](https://github.com/NewWays-TechForImpactKAIST/API-scrap-and-analysis/pull/53#issuecomment-1808103676)
